-- DB생성

CREATE TABLESPACE myts DATAFILE
'C:\app\USER01\oradata\myoracle\myts.dbf' SIZE 100M AUTOEXTEND ON NEXT 5M;

-- 계정생성
CREATE USER ora_user IDENTIFIED BY hong
DEFAULT TABLESPACE myts
TEMPORARY TABLESPACE TEMP;

-- 권한설정
GRANT DBA TO ORA_USER;